{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b448dd04-5963-430e-b848-9a8646f2f91c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter url of a Medium article:  https://medium.com/@subashgandyer/papa-what-is-a-neural-network-c5e5cc427c7\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "File saved at: scraped_articles\\papa-what-is-a-neural-network-c5e5cc427c7.txt\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import requests\n",
    "import re\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "\n",
    "# ---------------- FETCH PAGE ----------------\n",
    "def get_page():\n",
    "    global url\n",
    "\n",
    "    try:\n",
    "        url = input(\"Enter url of a Medium article: \").strip()\n",
    "\n",
    "        #  validate Medium URL only\n",
    "        if not re.match(r'https?://medium\\.com/', url):\n",
    "            raise ValueError(\"Please enter a valid Medium article URL\")\n",
    "\n",
    "        #  convert to Jina reader URL\n",
    "        jina_url = \"https://r.jina.ai/\" + url\n",
    "\n",
    "        headers = {\n",
    "            \"User-Agent\": \"Mozilla/5.0\",\n",
    "            \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\",\n",
    "        }\n",
    "\n",
    "        session = requests.Session()\n",
    "        response = session.get(jina_url, headers=headers, timeout=15)\n",
    "        response.raise_for_status()\n",
    "\n",
    "        return BeautifulSoup(response.text, \"html.parser\")\n",
    "\n",
    "    except ValueError as ve:\n",
    "        print(\"Input Error:\", ve)\n",
    "\n",
    "    except requests.exceptions.Timeout:\n",
    "        print(\"Request timed out. Try again.\")\n",
    "\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(\"Network/HTTP Error:\", e)\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"Unexpected error:\", e)\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "# ---------------- EXTRACT TEXT (ROBUST) ----------------\n",
    "def collect_text(soup):\n",
    "    if soup is None:\n",
    "        return \"No data scraped due to earlier error.\"\n",
    "\n",
    "    output = f\"url: {url}\\n\\n\"\n",
    "\n",
    "    # Try structured extraction first\n",
    "    tags = soup.find_all([\"h1\", \"h2\", \"h3\", \"p\"])\n",
    "\n",
    "    content = []\n",
    "\n",
    "    for tag in tags:\n",
    "        text = tag.get_text(strip=True)\n",
    "        if text:\n",
    "            content.append(text)\n",
    "\n",
    "    # Fallback if structured parsing fails\n",
    "    if not content:\n",
    "        raw_text = soup.get_text(separator=\"\\n\", strip=True)\n",
    "\n",
    "        if raw_text:\n",
    "            return output + raw_text\n",
    "        else:\n",
    "            return output + \"No readable content found.\"\n",
    "\n",
    "    # Clean join\n",
    "    return output + \"\\n\\n\".join(content)\n",
    "\n",
    "\n",
    "# ---------------- SAVE FILE ----------------\n",
    "def save_file(text):\n",
    "    try:\n",
    "        folder = \"scraped_articles\"\n",
    "\n",
    "        if not os.path.exists(folder):\n",
    "            os.makedirs(folder)\n",
    "\n",
    "        # safe filename\n",
    "        name = url.split(\"/\")[-1]\n",
    "        file_path = os.path.join(folder, f\"{name}.txt\")\n",
    "\n",
    "        with open(file_path, \"w\", encoding=\"utf-8\") as f:\n",
    "            f.write(text)\n",
    "\n",
    "        print(f\"\\nFile saved at: {file_path}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"Error while saving file:\", e)\n",
    "\n",
    "\n",
    "# ---------------- MAIN ----------------\n",
    "if __name__ == \"__main__\":\n",
    "    soup = get_page()\n",
    "    text = collect_text(soup)\n",
    "    save_file(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "82e781be-86f9-49b2-b994-3b5f28f1338f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c4a07ba-a275-4ed6-8817-cbdde8308711",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
